version: '3.7'

services:
  appName-db:
    container_name: appName-db-dev-local
    ports:
      - '33060:3306'

  appName-php:
    container_name: appName-php-dev-local
    ports:
      - '2222:22'
    volumes:
      - appName-api-app-sync:/app
    environment:
      APP_ENV: dev
      APP_VERSION: dev
      DATABASE_URL: mysql://root:@appName-db:3306/appName

  appName-nginx:
    container_name: appName-nginx-dev-local
    ports:
      - '9090:80'
    volumes:
      - appName-api-app-sync:/app

volumes:
  appName-api-app-sync:
    external: true
